"""Shared helpers for the procedural asset pipeline (charter §9 P5).

Every model in client/Content is generated by a script in this directory —
assets are versioned as code, not as binaries. Run headlessly:

    /Applications/Blender.app/Contents/MacOS/Blender -b -P tools/assets/missile.py

Conventions:
  - Units: meters. +Y is the model's forward axis, +Z is up (the UE importer
    remaps axes at import; the sim's ENU frame also treats +Y as "ahead").
  - Each generator builds SM_<Name>_LOD0..3 from the SAME parameters with
    per-LOD segment counts — the poly budget is a generator input, never an
    afterthought (charter §11 v2.1 비주얼 과중 통제).
  - Outputs land in tools/assets/out/ (gitignored): one FBX per LOD plus
    Workbench preview renders for the edit-render-inspect loop.
"""

import math
import os

import bmesh
import bpy
from mathutils import Matrix, Vector

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "out")


def reset_scene():
    """Empty scene with meter units — generators always start from nothing."""
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.unit_settings.system = "METRIC"
    scene.unit_settings.scale_length = 1.0


def new_object(name, bm):
    """Bake a bmesh into a linked object and free the bmesh."""
    mesh = bpy.data.meshes.new(name)
    bm.to_mesh(mesh)
    bm.free()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    return obj


def tangent_ogive_profile(length, radius, samples):
    """(forward_offset, radius) pairs for a tangent-ogive nose, base to tip."""
    rho = (radius**2 + length**2) / (2.0 * radius)  # Ogive circle radius.
    points = []
    for i in range(samples + 1):
        y = length * i / samples
        r = math.sqrt(max(rho**2 - y**2, 0.0)) + radius - rho
        points.append((y, max(r, 0.0)))
    return points


def revolve(name, profile, segments):
    """Revolve a (y, radius) profile around +Y into a closed solid."""
    bm = bmesh.new()
    chain = [bm.verts.new((0.0, y, r)) for (y, r) in profile]
    bm.verts.ensure_lookup_table()
    edges = [bm.edges.new((chain[i], chain[i + 1])) for i in range(len(chain) - 1)]
    bmesh.ops.spin(
        bm,
        geom=chain + edges,
        cent=(0.0, 0.0, 0.0),
        axis=(0.0, 1.0, 0.0),
        angle=2.0 * math.pi,
        steps=segments,
        use_merge=True,
        use_duplicate=False,
    )
    bmesh.ops.remove_doubles(bm, verts=bm.verts, dist=1e-5)
    # Cap whatever open boundaries remain (blunt tail/nose rings).
    boundary = [e for e in bm.edges if e.is_boundary]
    if boundary:
        bmesh.ops.holes_fill(bm, edges=boundary)
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    return new_object(name, bm)


def loft(name, sections):
    """Bridge a list of (y, ring) sections into a closed hull. Every ring is
    a list of (x, z) points with the SAME count, wound consistently; the end
    sections are capped with n-gons (transom / stem)."""
    bm = bmesh.new()
    rings = []
    for y, ring in sections:
        rings.append([bm.verts.new((x, y, z)) for (x, z) in ring])
    for a, b in zip(rings, rings[1:]):
        for i in range(len(a)):
            j = (i + 1) % len(a)
            bm.faces.new((a[i], a[j], b[j], b[i]))
    bm.faces.new(tuple(reversed(rings[0])))
    bm.faces.new(tuple(rings[-1]))
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    return new_object(name, bm)


def slanted_box(name, y0, y1, width, z0, z1, slope_deg=10.0, end_slope_deg=None,
                center_x=0.0):
    """Axis-aligned block whose walls lean inward toward the top — the basic
    low-RCS facet. slope_deg tilts the sides, end_slope_deg the fore/aft
    faces (defaults to the side slope)."""
    if end_slope_deg is None:
        end_slope_deg = slope_deg
    side_inset = (z1 - z0) * math.tan(math.radians(slope_deg))
    end_inset = (z1 - z0) * math.tan(math.radians(end_slope_deg))
    half = width / 2.0
    bm = bmesh.new()
    bottom = [
        bm.verts.new((center_x - half, y0, z0)),
        bm.verts.new((center_x + half, y0, z0)),
        bm.verts.new((center_x + half, y1, z0)),
        bm.verts.new((center_x - half, y1, z0)),
    ]
    top = [
        bm.verts.new((center_x - half + side_inset, y0 + end_inset, z1)),
        bm.verts.new((center_x + half - side_inset, y0 + end_inset, z1)),
        bm.verts.new((center_x + half - side_inset, y1 - end_inset, z1)),
        bm.verts.new((center_x - half + side_inset, y1 - end_inset, z1)),
    ]
    bm.faces.new(tuple(reversed(bottom)))
    bm.faces.new(tuple(top))
    for i in range(4):
        j = (i + 1) % 4
        bm.faces.new((bottom[i], bottom[j], top[j], top[i]))
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    return new_object(name, bm)


def cylinder(name, radius, length, segments, location=(0, 0, 0), pitch_deg=0.0):
    """Capped cylinder along +Y, optionally pitched up (gun barrels)."""
    bm = bmesh.new()
    bmesh.ops.create_cone(
        bm,
        cap_ends=True,
        radius1=radius,
        radius2=radius,
        depth=length,
        segments=segments,
    )
    bmesh.ops.rotate(
        bm,
        verts=bm.verts,
        cent=(0, 0, 0),
        matrix=Matrix.Rotation(math.radians(-(90.0 - pitch_deg)), 3, "X"),
    )
    bmesh.ops.translate(bm, vec=Vector(location) + Vector((0, length / 2.0, 0)), verts=bm.verts)
    obj = new_object(name, bm)
    return obj


def vcylinder(name, radius, height, segments, location=(0, 0, 0), smooth=True):
    """Capped cylinder standing vertically along +Z — radome drums, mooring bollards,
    capstans, funnel uptakes. (`cylinder` lies along +Y; this one stands up.) Sits on
    its base at `location`. Smooth-shaded by default so it reads round."""
    bm = bmesh.new()
    bmesh.ops.create_cone(
        bm, cap_ends=True, radius1=radius, radius2=radius, depth=height, segments=segments
    )
    bmesh.ops.translate(bm, vec=Vector(location) + Vector((0.0, 0.0, height / 2.0)), verts=bm.verts)
    obj = new_object(name, bm)
    if smooth:
        for poly in obj.data.polygons:
            poly.use_smooth = True
    return obj


def dome(name, radius, segments, location=(0, 0, 0), squash=0.7):
    """Smoothed radar/SATCOM radome: a UV-sphere clipped at the equator (lower half
    dropped, the flat base capped), squashed in Z, standing on its base at `location`.
    Smooth-shaded so it reads ROUND against the faceted superstructure — the rounded
    counterpoint that keeps the stealth facets from reading as a uniform greybox."""
    bm = bmesh.new()
    bmesh.ops.create_uvsphere(
        bm, u_segments=segments, v_segments=max(segments // 2, 4), radius=radius
    )
    lower = [v for v in bm.verts if v.co.z < -1e-4]
    if lower:
        bmesh.ops.delete(bm, geom=lower, context="VERTS")
    for v in bm.verts:
        v.co.z *= squash
    boundary = [e for e in bm.edges if e.is_boundary]
    if boundary:
        bmesh.ops.holes_fill(bm, edges=boundary)
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    bmesh.ops.translate(bm, vec=Vector(location), verts=bm.verts)
    obj = new_object(name, bm)
    for poly in obj.data.polygons:
        poly.use_smooth = True
    return obj


def fin(name, outline, thickness):
    """Extrude a planar (y, z) outline into a thin radial fin along +-X."""
    bm = bmesh.new()
    verts = [bm.verts.new((-thickness / 2.0, y, z)) for (y, z) in outline]
    face = bm.faces.new(verts)
    result = bmesh.ops.extrude_face_region(bm, geom=[face])
    extruded = [g for g in result["geom"] if isinstance(g, bmesh.types.BMVert)]
    bmesh.ops.translate(bm, vec=(thickness, 0.0, 0.0), verts=extruded)
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    return new_object(name, bm)


def radial_copies(obj, count, offset_deg=0.0):
    """Rotate-duplicate an object around +Y; returns all instances."""
    instances = [obj]
    for i in range(1, count):
        copy = obj.copy()
        copy.data = obj.data.copy()
        bpy.context.collection.objects.link(copy)
        instances.append(copy)
    for i, instance in enumerate(instances):
        angle = math.radians(offset_deg + 360.0 * i / count)
        instance.matrix_world = Matrix.Rotation(angle, 4, "Y") @ instance.matrix_world
    return instances


def join(objects, name):
    """Join into one object (UE wants one static mesh per LOD)."""
    bpy.ops.object.select_all(action="DESELECT")
    for obj in objects:
        obj.select_set(True)
    bpy.context.view_layer.objects.active = objects[0]
    bpy.ops.object.join()
    joined = bpy.context.view_layer.objects.active
    joined.name = name
    joined.data.name = name
    return joined


def bevel_all(obj, offset=0.08, segments=1):
    """Chamfer every edge a little so the ship reads as manufactured metal with machined
    edges — not raw CG boxes (the single biggest 'greybox vs finished' geometry cue). A
    small offset + clamp_overlap keeps thin greebles/railings from self-intersecting. Run
    on the JOINED mesh; new chamfer faces stay flat (correct), original smooth flags survive."""
    bm = bmesh.new()
    bm.from_mesh(obj.data)
    bmesh.ops.bevel(
        bm,
        geom=list(bm.edges) + list(bm.verts),
        offset=offset,
        offset_type="OFFSET",
        segments=segments,
        profile=0.5,
        affect="EDGES",
        clamp_overlap=True,
    )
    bm.normal_update()
    bm.to_mesh(obj.data)
    bm.free()
    return obj


def cavity_ao(obj, cuts=1, samples=16, name="AO"):
    """Bake ambient occlusion into a per-corner vertex-color attribute so geometry junctions
    (block intersections, deck-edge recesses, the base of every vertical face) DARKEN by
    occlusion — the 'cavity AO' that breaks a flat-albedo 'putty monolith' read (naval-AD). The
    UE material multiplies base color by this vertex color. A light subdivision gives the AO a
    gradient to fall across the big flat faces; run AFTER join+bevel, LOD0/1 only (hero cost).
    Returns obj. Cycles AO bake to VERTEX_COLORS — geometry-only, needs no UVs."""
    bpy.ops.object.select_all(action="DESELECT")
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj
    if cuts > 0:
        bpy.ops.object.mode_set(mode="EDIT")
        bpy.ops.mesh.select_all(action="SELECT")
        bpy.ops.mesh.subdivide(number_cuts=cuts)
        bpy.ops.object.mode_set(mode="OBJECT")
    me = obj.data
    if name not in (a.name for a in me.color_attributes):
        me.color_attributes.new(name=name, type="BYTE_COLOR", domain="CORNER")
    me.color_attributes.active_color = me.color_attributes[name]
    scene = bpy.context.scene
    scene.render.engine = "CYCLES"
    try:
        scene.cycles.device = "CPU"
    except Exception:  # noqa: BLE001
        pass
    scene.cycles.samples = samples
    scene.render.bake.target = "VERTEX_COLORS"
    bpy.ops.object.bake(type="AO")
    return obj


def material(name, base_color, roughness=0.6, metallic=0.3):
    mat = bpy.data.materials.get(name)
    if mat is not None:
        return mat
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = (*base_color, 1.0)
    bsdf.inputs["Roughness"].default_value = roughness
    bsdf.inputs["Metallic"].default_value = metallic
    return mat


def assign_material(obj, mat, faces_where=None):
    """Append a material; optionally restrict to faces selected by a predicate
    on the face center (Vector) — used e.g. to darken a radome tip."""
    obj.data.materials.append(mat)
    if faces_where is None:
        return
    slot = len(obj.data.materials) - 1
    for poly in obj.data.polygons:
        if faces_where(Vector(poly.center)):
            poly.material_index = slot


def shade_smooth(obj, angle_deg=35.0):
    bpy.ops.object.select_all(action="DESELECT")
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.shade_smooth()
    bpy.ops.object.shade_auto_smooth(angle=math.radians(angle_deg))


def export_fbx(obj, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    bpy.ops.object.select_all(action="DESELECT")
    obj.select_set(True)
    bpy.ops.export_scene.fbx(
        filepath=path,
        use_selection=True,
        apply_scale_options="FBX_SCALE_ALL",
        bake_space_transform=True,
    )


def render_previews(prefix, subject_size, angles=((30, 60), (10, 0), (45, -130))):
    """Workbench renders from several (elevation°, azimuth°) viewpoints —
    the inspect half of the edit-render-inspect loop. Azimuth 0 is the +X
    side (pure profile, since models face +Y); 60 is a front quarter and
    -130 a rear quarter."""
    scene = bpy.context.scene
    scene.render.engine = "BLENDER_WORKBENCH"
    scene.display.shading.light = "STUDIO"
    scene.display.shading.show_cavity = True
    scene.display.shading.color_type = "MATERIAL"
    scene.render.resolution_x = 1280
    scene.render.resolution_y = 960
    scene.render.film_transparent = False
    scene.world = bpy.data.worlds.new("PreviewWorld")
    scene.world.color = (0.18, 0.20, 0.23)

    camera = bpy.data.cameras.new("PreviewCam")
    cam_obj = bpy.data.objects.new("PreviewCam", camera)
    bpy.context.collection.objects.link(cam_obj)
    scene.camera = cam_obj

    os.makedirs(os.path.dirname(prefix), exist_ok=True)
    distance = subject_size * 1.4
    paths = []
    for elevation_deg, azimuth_deg in angles:
        elevation = math.radians(elevation_deg)
        azimuth = math.radians(azimuth_deg)
        location = Vector(
            (
                distance * math.cos(elevation) * math.cos(azimuth),
                distance * math.cos(elevation) * math.sin(azimuth),
                distance * math.sin(elevation),
            )
        )
        cam_obj.location = location
        cam_obj.rotation_euler = (-location).to_track_quat("-Z", "Y").to_euler()
        path = f"{prefix}_e{elevation_deg}_a{abs(azimuth_deg)}.png"
        scene.render.filepath = path
        bpy.ops.render.render(write_still=True)
        paths.append(path)
    return paths
